<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestStringVerification-resultado Média" tests="3" file=".py" time="0.020" timestamp="2024-09-17T14:49:38" failures="3" errors="0" skipped="0">
	<testcase classname="TestStringVerification" name="test_verificar_string_1" time="0.018" timestamp="2024-09-17T14:49:38" file="test.py" line="40">
		<failure type="AssertionError" message="False is not true"><![CDATA[Traceback (most recent call last):
  File "/home/fernando/Área de Trabalho/Projeto/Repositorio_IC/IC/Variáveis e estrutura sequencial/Média ponderada/Testes/test.py", line 42, in test_verificar_string_1
    self.assertTrue(verificar_string("6.7", valores_entrada,self.file))
AssertionError: False is not true
]]></failure>
	</testcase>
	<testcase classname="TestStringVerification" name="test_verificar_string_2" time="0.001" timestamp="2024-09-17T14:49:38" file="test.py" line="44">
		<failure type="AssertionError" message="False is not true"><![CDATA[Traceback (most recent call last):
  File "/home/fernando/Área de Trabalho/Projeto/Repositorio_IC/IC/Variáveis e estrutura sequencial/Média ponderada/Testes/test.py", line 46, in test_verificar_string_2
    self.assertTrue(verificar_string("30.0", valores_entrada,self.file))
AssertionError: False is not true
]]></failure>
	</testcase>
	<testcase classname="TestStringVerification" name="test_verificar_string_3" time="0.001" timestamp="2024-09-17T14:49:38" file="test.py" line="48">
		<failure type="AssertionError" message="False is not true"><![CDATA[Traceback (most recent call last):
  File "/home/fernando/Área de Trabalho/Projeto/Repositorio_IC/IC/Variáveis e estrutura sequencial/Média ponderada/Testes/test.py", line 50, in test_verificar_string_3
    self.assertTrue(verificar_string("7.8", valores_entrada,self.file))
AssertionError: False is not true
]]></failure>
	</testcase>
</testsuite>
